apiVersion: v1
kind: Service
metadata:
  name: murmur
  namespace: sestream
spec:
  type: NodePort 
  selector:
    app: murmur  
  ports:
    - protocol: TCP
      nodePort: 30004
      port: 80        