apiVersion: apps/v1
kind: Deployment
metadata:
  name: murmur
  namespace: sestream
  labels:
    app: murmur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: murmur
  template:
    metadata:
      labels:
        app: murmur
    spec:
      serviceAccountName: service-account
      containers:
        - name: sestream
          image: 392223633930.dkr.ecr.us-west-2.amazonaws.com/murmur:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: SAMPLE_RATE
              value: "16000"
            - name: BUFFER_MIN_S
              value: "1.5"
            - name: BUFFER_MAX_S
              value: "5.0"
            - name: SILENCE_THRESHOLD_RMS
              value: "0.01"
            - name: REDIS_HOST
              value: reids
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: OPENAI_API_KEY
      tolerations:
        - key: pool
          operator: Equal
          value: murmur
          effect: NoSchedule