apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: sestream
  namespace: sestream
spec:
  targetGroupARN: arn:aws:elasticloadbalancing:us-west-2:392223633930:targetgroup/murmurstack/832a2766e4179d4c
  serviceRef:
    name: sestream
    port: 80