apiVersion: apps/v1
kind: Deployment
metadata:
  name: sestream
  namespace: sestream
  labels:
    app: sestream
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sestream
  template:
    metadata:
      labels:
        app: sestream
    spec:
      containers:
        - name: sestream
          image: 392223633930.dkr.ecr.us-west-2.amazonaws.com/sestream:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DEBUG_MODE
              value: "false"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: OPENAI_API_KEY
      tolerations:
        - key: pool
          operator: Equal
          value: sestream
          effect: NoSchedule