apiVersion: v1
kind: Service
metadata:
  name: sestream
  namespace: sestream
spec:
  type: NodePort 
  selector:
    app: sestream  
  ports:
    - protocol: TCP
      nodePort: 30003
      port: 80        