[project]
name = "demo-server"
version = "0.1.0"
description = "Serving requests for demo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "openai>=1.77.0",
]
