[project]
name = "demo-server"
version = "0.1.0"
description = "Serving requests for demo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "fastapi[standard]>=0.115.12",
    "numpy>=2.2.5",
    "openai>=1.77.0",
    "websockets>=15.0.1",
]
